# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEMq4t6wJCmlr3DBRYi9ogrVfEA3HLqP
"""

import resource, sys
resource.setrlimit(resource.RLIMIT_STACK, (229, -1))
sys.setrecursionlimit(107)

from collections import deque

def solve():

    dx = [1, -1, 0, 0, 1, 1, -1, -1]
    dy = [0, 0, 1, -1, 1, -1, 1, -1]
    n, m = [int(x) for x in input().split()] 

    mt = [[] for x in range(n)] 
    for i in range(n):
        mt[i] = list(input())

    v = [[False for y in range(m)] for x in range(n)]

    st = deque()
 
    def valid(r, c):
        rt = (r >= 0) and (r < n)
        rt = rt and (c >= 0) and (c < m)
        if not rt: return False 
        rt = rt and (mt[r][c] == '@') and (not v[r][c])
        return rt

    def dfs(r, c): 
        v[r][c] = True
        st.append((r, c))
        while len(st):
            r, c = st.popleft()
            v[r][c] = True
            for i in range(8):
                nr, nc = r + dx[i], c + dy[i]
                if valid(nr, nc):
                    v[nr][nc] = True
                    st.append((nr, nc))
    re= 0
    for i in range(n):
        for j in range(m):
            if (mt[i][j] == '@') and (not v[i][j]):
                re += 1
                dfs(i, j)
    return re

print(solve())